### ISSUE TITLE
Enlace y usuario demo para grafana

### ISSUE THREAD

**Issue by dalogax** [aindustriosa/FinTrack#4]
Hola, trabajazo!! enhorabuena por el proyecto, lo estuve probando y funciona de lujo. Muchas gracias.
Podríais poner en la wiki el enlace a grafana y un usuario para poder visualizar nuestros ficheros?

**Comment by j-lorenzo** [comment]
Sí, lo cierto es que hemos hecho pruebas con nuestro barco y no podemos visualizarlas, interesa también!
